# Generated by Django 5.0.2 on 2024-09-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=100)),
                ('nom_ape', models.CharField(max_length=100)),
                ('fuerza', models.CharField(max_length=100)),
                ('unidad', models.CharField(max_length=100)),
                ('cargo_actual', models.CharField(max_length=100)),
                ('tel_oficina', models.CharField(max_length=100)),
                ('tel_ip', models.CharField(max_length=100)),
                ('tel_celular', models.CharField(max_length=100)),
                ('correo_inst', models.EmailField(max_length=100)),
                ('correo_personal', models.EmailField(max_length=100)),
            ],
        ),
    ]
